language: java

jdk:
  - oraclejdk8

install:
 - wget http://bob.nem.ninja/nem-core__V0.4.21-BETA.jar
 - mvn install:install-file -Dfile=nem-core__V0.4.21-BETA.jar -DgroupId=org.nem.core -DartifactId=nem-core -Dversion=0.4.21-BETA -Dpackaging=jar
